# Generated by Django 4.1.7 on 2023-05-16 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beerbuddies_app', '0003_rename_post_rating_restaurant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='RestaurantRating',
        ),
        migrations.CreateModel(
            name='BeerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beerbuddies_app.beer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
