# Generated by Django 4.2 on 2023-05-16 18:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beerbuddies_app", "0004_rename_rating_restaurantrating_beerrating"),
    ]

    operations = [
        migrations.AddField(
            model_name="app_user",
            name="beer_preferences",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="app_user",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="app_user",
            name="state",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
