# Generated by Django 4.2 on 2023-05-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerbuddies_app', '0005_beer_remove_beer_garden_beer_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer_garden',
            name='beer',
        ),
        migrations.AddField(
            model_name='beer_garden',
            name='beers',
            field=models.ManyToManyField(related_name='beer_gardens', to='beerbuddies_app.beer'),
        ),
    ]
