# Generated by Django 4.2 on 2023-05-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beerbuddies_app", "0005_app_user_beer_preferences_app_user_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="app_user",
            name="beer_preferences",
        ),
        migrations.AddField(
            model_name="app_user",
            name="beer_preference",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
