# Generated by Django 4.2 on 2023-05-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerbuddies_app', '0006_remove_beer_garden_beer_beer_garden_beers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer_garden',
            name='beers',
        ),
        migrations.AddField(
            model_name='beer',
            name='beer_garden',
            field=models.ManyToManyField(related_name='beer_gardens', to='beerbuddies_app.beer_garden'),
        ),
    ]
