# Generated by Django 4.2 on 2023-05-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerbuddies_app', '0007_remove_beer_garden_beers_beer_beer_garden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer_garden',
            name='user',
        ),
        migrations.AlterField(
            model_name='app_user',
            name='token_amount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name='Beer',
        ),
        migrations.DeleteModel(
            name='Beer_Garden',
        ),
    ]
