# Generated by Django 4.2 on 2023-05-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerbuddies_app', '0008_remove_beer_garden_user_alter_app_user_token_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abv', models.DecimalField(decimal_places=1, max_digits=4)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='app_user',
            name='profile_info',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='app_user',
            name='token_amount',
            field=models.IntegerField(default=0),
        ),
    ]
