# Generated by Django 4.2 on 2023-05-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerbuddies_app', '0009_beer_alter_app_user_profile_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
